### ISSUE TITLE
Inside Measurement

### ISSUE THREAD

**Issue by Mechasparrow** [mizzou-capstone-capybaras-2022/capybara-campus-crawl#9]

**Comment by Mechasparrow** [comment]
https://docs.google.com/spreadsheets/d/1Xl_XM_VXwKhqEfVrRQLTYFuKCx0O5Jq9VTvANYw6dLM/edit#gid=0

**Comment by rjgxfv** [comment]
Buildings Left to do: 
Hill Hall
London Hall
Tucker Hall
Townsend Hall
